
export const submitData =
{
    "applicationForm": {
    "countryCode": "mm",
    "irn": "3734",
    "breedersReference": "37D4",
    "schemaVersion": "1.0",
    "sourceApplication": "prisma",
    "status": "SUBMITTED",
    "applicationNumber": "",
    "filingDate": "",
    "priorityDate": "2021-09-23",
    "feesPaid": "",
    "dateFeesPaid": "",
    "dateReceipt": "",
    "formalityMet": "",
    "dateFormalityResponse": "",
    "denominationAccepted": "",
    "dateDenomResponse": "",
    "noveltySatisfied": "",
    "dateNoveltyResponse": "",
    "priorityClaimAccepted": "",
    "datePriorityClaimResponse": "",
    "dateSubmission": "2021-09-23",
    "dateStatusChange": "",
    "proposedDenomination": "Ardinas",
    "formalityApplicantFlag": "",
    "formalityPRFlag": "",
    "formalityOtherFlag": "",
    "ownerId": "MADHOUR",
    "isSold": "yes",
    "authFirstApp": "JSDHFJ287",
    "authFirstCommercialisation": "GFJ685",
    "dateFirstCommercialisation": "2020-09-23",
    "submitterReference": "11EJ",
    "paymentOfficeStatus": "pending",
    "paymentNumber": "9213697NHKJSFDG",
    "paymentStatus": "paid",
    "languageNumberAf": "792849",
    "languageNumberTq": "6346",
    "upovCodeId": "54HH33V",
    "agent": "33VHGJ312",
    "userCommonName": "Lettuce",
    "applicationType": "PBR",
    "botanicalName": "Lactuca sativa L.",
    "dusFlag": "",
    "dusExaminationStatus": "",
    "dusDecisionDate": "",
    "isObjection": "FALSE",
    "grantDate": "",
    "grantNumber": "",
    "holder": "REGJJ22",
    "maintainer": "JFAH33",
    "breeder": "DSUR342",
    "applicant": "SD133VH"
    },
    "attachmentMetaData": {
    "attachmentsCount": 2,
    "attachmentsName": ["tq.pdf","application.xml"],
    "zipSize": 510759,
    "zipName": "patent.zip"
    },
    "authority": "mm"
    }
